name: Build VTosters Lite

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - uses: actions/checkout@v3
      
      - name: Download tools
        run: |
          sudo apt update
          sudo apt install default-jre
          sudo apt install python3
          sudo apt install zipalign
          chmod +x scripts/apktool.jar
          chmod +x scripts/apksigner.jar
          rustup target add armv7-linux-androideabi
          rustup target add aarch64-linux-android 
          
      - name: Build VTLite
        run: |
          gradle generateBuildTasks
          gradle prepareDexForMergeDev
          java -jar scripts/apktool.jar b smali -o smali/VTLite.apk --use-aapt2 -p scripts/framework/
          zipalign -p -f 4 smali/VTLite.apk smali/VTLite.apk_aligned
          mv smali/VTLite.apk_aligned smali/VTLite.apk

      - name: Sign and verify the apk
        run: |
          java -jar scripts/apksigner.jar sign --ks scripts/debug.keystore --ks-key-alias androiddebugkey --ks-pass pass:android smali/VTLite.apk
          java -jar scripts/apksigner.jar verify smali/VTLite.apk
                      
      - name: Upload apk to artifact
        uses: actions/upload-artifact@v3
        with:
          name: VTLite.apk
          path: smali/VTLite.apk
